apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipelines-wrap-resolvers-namespace-rbac
  namespace: tekton-pipelines-resolvers
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental-wrap-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-pipelines-wrap-resolvers
    namespace: tekton-pipelines-resolvers
roleRef:
  kind: Role
  name: tekton-pipelines-wrap-resolvers-namespace-rbac
  apiGroup: rbac.authorization.k8s.io
