on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

name: build-test-publish

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  publish:
    name: publish latest
    runs-on: ubuntu-latest
    needs: [ build ]

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/checkout@v2

    - id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}/base
        flavor: |
          latest=true
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: ./images/base

    - uses: imjasonh/setup-ko@v0.4
    - run: ko publish --push=${{ github.event_name != 'pull_request' }} --base-import-paths ./cmd/...
