on:
  pull_request:
    branches: [ main ]

name: Build latest images

jobs:
  build:
    name: publish latest
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/checkout@v2
    - uses: imjasonh/setup-ko@v0.4
    - run: ko publish --push=false --base-import-paths ./cmd/...
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        push: false
        tags: ghcr.io/vdemeester/tekton-oci-pipeline/base:latest
        context: ./images/base
